#!/bin/bash
target=test.frish

set -eE
export dtree_tool=${HOME}/projects/dtree
${PBP}/resetlog
export T2TVERBOSE=on

# # create xinterpret.frish from xinterpret.drawio
# ${dtree_tool}/@make ${dtree_tool} "xinterpret" $(pwd)

# # insert generated code (`xinterpret.frish`) into forthish.frish
# ${PBP}/include forthish.frish.inc | tr -d '\r' > forthish.frish

# transmogrify `forthish.frish` into `forthish.py`
${PBP}/das2json frish.drawio
clear
echo
echo "--- using ${target} --------"
echo "in @dev-makec ${T2TVERBOSE}"
echo
python main.py ${target} main frish.drawio.json | ${PBP}/splitoutputs
mv out.1.py forthish.py
echo

