#!/bin/bash
target=test.frish
export T2TVERBOSE=on
clear
echo
echo "--- using ${target} --------"
echo "in @dev-makec T2TVERBOSE=${T2TVERBOSE}"
echo

set -eE
export dtree_tool=${HOME}/projects/dtree

# # create xinterpret.frish from xinterpret.drawio
# ${dtree_tool}/@make ${dtree_tool} "xinterpret" $(pwd)

# # insert generated code (`xinterpret.frish`) into forthish.frish
# ${PBP}/include forthish.frish.inc | tr -d '\r' > forthish.frish

# transmogrify `forthish.frish` into `forthish.py`
${PBP}/das2json frish.drawio
python main.py ${target} main frish.drawio.json | ${PBP}/splitoutputs
mv out.1.py forthish.py
echo

