#!/bin/bash
set -eE
trap '[ -f "out.✗" ] && cat "out.✗"' ERR
export dtree_tool=${HOME}/projects/dtree
${PBP}/resetlog

# create xinterpret.frish from xinterpret.drawio
${dtree_tool}/@make ${dtree_tool} "xinterpret" $(pwd)

# insert generated code (`xinterpret.frish`) into forthish.frish
m4 forthish.frish.m4 | tr -d '\r' > forthish.frish

# transmogrify `forthish.frish` into `forthish.py`
${PBP}/das2json frish.drawio
python main.py forthish.frish main frish.drawio.json | ${PBP}/splitoutputs
	 
